DROP DATABASE IF EXISTS LoginDB;
CREATE DATABASE IF NOT EXISTS LoginDB; 

USE LoginDB;

DROP TABLE IF EXISTS User;

CREATE TABLE User (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    userName VARCHAR(255) NOT NULL,
    userEmail VARCHAR(255) NOT NULL,
    userPassword VARCHAR(255) NOT NULL
);